# =============================================================================
# SUB NODE #3  —  SERVERINDEX=3  ·  nginx :9350  ·  Node.js :9300
# =============================================================================

server {
    listen 9350;                                  # (1)
    server_name localhost;

    set $node_api 127.0.0.1:9300;                 # (2)

    root D:/gitrepos/Stream-Sub-Server-3;         # (3)

    include stream-node-body.conf;
}
